theme: jekyll-theme-cayman

title: [Fundamentos Procesamiento de Lenguaje Natural (NLP)]
description: [Repositorio para la clase electiva Fundamentos de Procesamiento de Lenguaje Natural (NLP) 2020-II | Konrad Lorenz Fundación Universitaria]
